name: Pull Request

on:
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest
    environment: PR

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install prerequisites
        run: |
          chmod +x docker/install-prerequisites.sh
          ./docker/install-prerequisites.sh
          echo "$HOME/.bun/bin" >> $GITHUB_PATH
          echo "$HOME/.bun/global/bin" >> $GITHUB_PATH

      - name: Install dependencies
        working-directory: src
        run: bun install

      - name: Run anonymous tests
        working-directory: src
        run: bun test --test-name-pattern "anonymous"